### ISSUE TITLE
better handling of default css (was "How do I work this?")

### ISSUE THREAD

**Issue by megabulk** [unveillance/UnveillanceInterface#3]
I want to make a few small changes to this repo. (Get rid of type.css (why does it dictate the font and color for the whole site? Why?) and add a reset.css file to zero out the styles) I forked it from https://github.com/harlo/UnveillanceInterface a long time ago. What's the best way to do this?

**Comment by harlo** [comment]
I give you full permission to make those changes, but the core unveillance interface package should have default fonts/color schemes that may be overridden by css added to any project that incorporates it as a submodule.

**Comment by megabulk** [comment]
I guess it’s more that that file should load _before_ the users’ css, so it can be overridden. When it loads after, then it overrides everything else.

**Comment by megabulk** [comment]
And yes, we need a "reset" CSS, to start from scratch and make it consistent across browsers. Here's the one I've been using for years: I don't know if it's the best, but it does the job.

``` CSS
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, font, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td, hr {
    margin: 0;
    padding: 0;
    border: 0;
    outline: 0;
    font-size: 100%;
    vertical-align: baseline;
    background: transparent;
    font-weight:normal;
}
strong, b {
    font-weight:bold;
}
body {
    line-height: 1;
}
ol, ul {
    list-style: none;
}
blockquote, q {
    quotes: none;
}

/* remember to define focus styles! */
:focus {
    outline: 0;
}

/* remember to highlight inserts somehow! */
ins {
    text-decoration: none;
}
del {
    text-decoration: line-through;
}

/* tables still need 'cellspacing="0"' in the markup */
table {
    border-collapse: collapse;
    border-spacing: 0;
}
```
